// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Sonorus.Business.Infrastructure.Persistence;

#nullable disable

namespace Sonorus.Business.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SonorusBusinessDbContext))]
    [Migration("20250214223548_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sonorus.Business.Core.Entities.Opportunity", b =>
                {
                    b.Property<long>("OpportunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OpportunityId"));

                    b.Property<DateTime>("AnnouncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("BandName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExperienceRequired")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsWork")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Payment")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("RecruiterId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("WorkTimeUnit")
                        .HasColumnType("tinyint");

                    b.HasKey("OpportunityId");

                    b.ToTable("Opportunities");
                });
#pragma warning restore 612, 618
        }
    }
}
