name: sonorus
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  flutter_mobx: ^2.0.6+5
  dio: ^5.1.2
  mobx: ^2.2.0
  flutter_modular: ^6.3.2
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  flutter_screenutil: ^5.9.0
  validatorless: ^1.2.3
  jwt_decoder: ^2.0.1
  carousel_slider: ^4.2.1
  signalr_core: ^1.1.1
  flutter_native_splash: ^2.3.3
  shimmer: ^3.0.0
  video_player: ^2.7.2
  flutter_staggered_grid_view: ^0.7.0
  convex_bottom_bar: ^3.2.0
  intl: ^0.18.1
  uuid: ^3.0.7
  video_thumbnail: ^0.5.3
  brasil_fields: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.3.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#16161F"
  image: assets/images/logo.png

flutter:
  assets:
    - .env
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: museoModerno
      fonts:
        - asset: assets/fonts/museoModerno/MuseoModerno-Thin.ttf
          weight: 100
        - asset: assets/fonts/museoModerno/MuseoModerno-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/museoModerno/MuseoModerno-Light.ttf
          weight: 300
        - asset: assets/fonts/museoModerno/MuseoModerno-Regular.ttf
          weight: 400
        - asset: assets/fonts/museoModerno/MuseoModerno-Medium.ttf
          weight: 500
        - asset: assets/fonts/museoModerno/MuseoModerno-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/museoModerno/MuseoModerno-Bold.ttf
          weight: 700
        - asset: assets/fonts/museoModerno/MuseoModerno-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/museoModerno/MuseoModerno-Black.ttf
          weight: 900

    # - family: robotoMono
    #   fonts:
    #     - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
    #       weight: 500

  uses-material-design: true