// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sonorus.BusinessAPI.Data.Context;

#nullable disable

namespace Sonorus.BusinessAPI.Migrations
{
    [DbContext(typeof(BusinessAPIDbContext))]
    [Migration("20231110023335_ImprovementColumnsWorkUnitInOpportunitiesTable")]
    partial class ImprovementColumnsWorkUnitInOpportunitiesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sonorus.BusinessAPI.Data.Entities.Opportunity", b =>
                {
                    b.Property<long>("OpportunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OpportunityId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsWork")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Payment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RecruiterId")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeExperience")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkTimeUnit")
                        .HasColumnType("int");

                    b.HasKey("OpportunityId");

                    b.ToTable("Opportunities");
                });
#pragma warning restore 612, 618
        }
    }
}
