// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sonorus.PostAPI.Data.Context;

#nullable disable

namespace Sonorus.PostAPI.Migrations
{
    [DbContext(typeof(PostAPIDbContext))]
    [Migration("20231206195247_UpdateLenghtColumnTablature")]
    partial class UpdateLenghtColumnTablature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterestsPosts", b =>
                {
                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long>("InterestId")
                        .HasColumnType("bigint");

                    b.HasKey("PostId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("InterestsPosts");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Comment", b =>
                {
                    b.Property<long?>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("CommentId"));

                    b.Property<DateTime>("CommentedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.CommentLiker", b =>
                {
                    b.Property<long>("CommentLikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CommentLikerId"));

                    b.Property<long?>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("CommentLikerId");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentLikers");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Interest", b =>
                {
                    b.Property<long>("InterestId")
                        .HasColumnType("bigint");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1L
                        },
                        new
                        {
                            InterestId = 2L
                        },
                        new
                        {
                            InterestId = 3L
                        },
                        new
                        {
                            InterestId = 4L
                        },
                        new
                        {
                            InterestId = 5L
                        },
                        new
                        {
                            InterestId = 6L
                        },
                        new
                        {
                            InterestId = 7L
                        },
                        new
                        {
                            InterestId = 8L
                        },
                        new
                        {
                            InterestId = 9L
                        },
                        new
                        {
                            InterestId = 10L
                        },
                        new
                        {
                            InterestId = 11L
                        },
                        new
                        {
                            InterestId = 12L
                        },
                        new
                        {
                            InterestId = 13L
                        },
                        new
                        {
                            InterestId = 14L
                        },
                        new
                        {
                            InterestId = 15L
                        },
                        new
                        {
                            InterestId = 16L
                        },
                        new
                        {
                            InterestId = 17L
                        },
                        new
                        {
                            InterestId = 18L
                        },
                        new
                        {
                            InterestId = 19L
                        },
                        new
                        {
                            InterestId = 20L
                        },
                        new
                        {
                            InterestId = 21L
                        },
                        new
                        {
                            InterestId = 22L
                        },
                        new
                        {
                            InterestId = 23L
                        },
                        new
                        {
                            InterestId = 24L
                        },
                        new
                        {
                            InterestId = 25L
                        },
                        new
                        {
                            InterestId = 26L
                        },
                        new
                        {
                            InterestId = 27L
                        },
                        new
                        {
                            InterestId = 28L
                        },
                        new
                        {
                            InterestId = 29L
                        },
                        new
                        {
                            InterestId = 30L
                        },
                        new
                        {
                            InterestId = 31L
                        },
                        new
                        {
                            InterestId = 32L
                        },
                        new
                        {
                            InterestId = 33L
                        },
                        new
                        {
                            InterestId = 34L
                        },
                        new
                        {
                            InterestId = 35L
                        },
                        new
                        {
                            InterestId = 36L
                        },
                        new
                        {
                            InterestId = 37L
                        },
                        new
                        {
                            InterestId = 38L
                        },
                        new
                        {
                            InterestId = 39L
                        },
                        new
                        {
                            InterestId = 40L
                        },
                        new
                        {
                            InterestId = 41L
                        },
                        new
                        {
                            InterestId = 42L
                        },
                        new
                        {
                            InterestId = 43L
                        },
                        new
                        {
                            InterestId = 44L
                        },
                        new
                        {
                            InterestId = 45L
                        },
                        new
                        {
                            InterestId = 46L
                        },
                        new
                        {
                            InterestId = 47L
                        },
                        new
                        {
                            InterestId = 48L
                        },
                        new
                        {
                            InterestId = 49L
                        });
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Media", b =>
                {
                    b.Property<long?>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("MediaId"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(41)
                        .HasColumnType("nvarchar(41)");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.HasKey("MediaId");

                    b.HasIndex("PostId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Post", b =>
                {
                    b.Property<long?>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("PostId"));

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("PostedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Tablature")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PostId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.PostLiker", b =>
                {
                    b.Property<long>("PostLikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PostLikerId"));

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PostLikerId");

                    b.HasIndex("PostId");

                    b.ToTable("PostLikers");
                });

            modelBuilder.Entity("InterestsPosts", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sonorus.PostAPI.Data.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Comment", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.CommentLiker", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Comment", null)
                        .WithMany("Likers")
                        .HasForeignKey("CommentId");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Media", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Post", "Post")
                        .WithMany("Medias")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.PostLiker", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Post", null)
                        .WithMany("Likers")
                        .HasForeignKey("PostId");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Comment", b =>
                {
                    b.Navigation("Likers");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likers");

                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
