// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sonorus.PostAPI.Data.Context;

#nullable disable

namespace Sonorus.PostAPI.Migrations
{
    [DbContext(typeof(PostAPIDbContext))]
    [Migration("20231012203947_TableCommentLikers")]
    partial class TableCommentLikers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterestPost", b =>
                {
                    b.Property<long>("InterestsIdInterest")
                        .HasColumnType("bigint");

                    b.Property<long>("PostsIdPost")
                        .HasColumnType("bigint");

                    b.HasKey("InterestsIdInterest", "PostsIdPost");

                    b.HasIndex("PostsIdPost");

                    b.ToTable("InterestPost");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Comment", b =>
                {
                    b.Property<long?>("IdComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("IdComment"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("IdPost")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.HasKey("IdComment");

                    b.HasIndex("IdPost");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.CommentLiker", b =>
                {
                    b.Property<long>("IdCommentLiker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCommentLiker"));

                    b.Property<long?>("CommentIdComment")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.HasKey("IdCommentLiker");

                    b.HasIndex("CommentIdComment");

                    b.ToTable("CommentLikers");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Interest", b =>
                {
                    b.Property<long>("IdInterest")
                        .HasColumnType("bigint");

                    b.HasKey("IdInterest");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Media", b =>
                {
                    b.Property<long?>("IdMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("IdMedia"));

                    b.Property<long>("IdPost")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(41)
                        .HasColumnType("nvarchar(41)");

                    b.HasKey("IdMedia");

                    b.HasIndex("IdPost");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Post", b =>
                {
                    b.Property<long?>("IdPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("IdPost"));

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tablature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPost");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.PostLiker", b =>
                {
                    b.Property<long>("IdPostLiker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPostLiker"));

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.Property<long?>("PostIdPost")
                        .HasColumnType("bigint");

                    b.HasKey("IdPostLiker");

                    b.HasIndex("PostIdPost");

                    b.ToTable("PostLikers");
                });

            modelBuilder.Entity("InterestPost", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestsIdInterest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sonorus.PostAPI.Data.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostsIdPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Comment", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.CommentLiker", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Comment", null)
                        .WithMany("Likers")
                        .HasForeignKey("CommentIdComment");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Media", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Post", "Post")
                        .WithMany("Medias")
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.PostLiker", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Post", null)
                        .WithMany("Likers")
                        .HasForeignKey("PostIdPost");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Comment", b =>
                {
                    b.Navigation("Likers");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likers");

                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
