// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sonorus.PostAPI.Data.Context;

#nullable disable

namespace Sonorus.PostAPI.Migrations
{
    [DbContext(typeof(PostAPIDbContext))]
    [Migration("20231031034336_FixManyToManyPostInterests")]
    partial class FixManyToManyPostInterests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterestsPosts", b =>
                {
                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long>("InterestId")
                        .HasColumnType("bigint");

                    b.HasKey("PostId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("InterestsPosts");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Comment", b =>
                {
                    b.Property<long?>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("CommentId"));

                    b.Property<DateTime>("CommentedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 10, 31, 0, 43, 35, 931, DateTimeKind.Local).AddTicks(6240));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.CommentLiker", b =>
                {
                    b.Property<long>("CommentLikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CommentLikerId"));

                    b.Property<long?>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("CommentLikerId");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentLikers");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Interest", b =>
                {
                    b.Property<long>("InterestId")
                        .HasColumnType("bigint");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1L
                        },
                        new
                        {
                            InterestId = 2L
                        },
                        new
                        {
                            InterestId = 3L
                        },
                        new
                        {
                            InterestId = 4L
                        },
                        new
                        {
                            InterestId = 5L
                        });
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Media", b =>
                {
                    b.Property<long?>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("MediaId"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(41)
                        .HasColumnType("nvarchar(41)");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.HasKey("MediaId");

                    b.HasIndex("PostId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Post", b =>
                {
                    b.Property<long?>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("PostId"));

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("PostedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 10, 31, 0, 43, 35, 931, DateTimeKind.Local).AddTicks(5793));

                    b.Property<string>("Tablature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PostId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.PostLiker", b =>
                {
                    b.Property<long>("PostLikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PostLikerId"));

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PostLikerId");

                    b.HasIndex("PostId");

                    b.ToTable("PostLikers");
                });

            modelBuilder.Entity("InterestsPosts", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sonorus.PostAPI.Data.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Comment", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.CommentLiker", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Comment", null)
                        .WithMany("Likers")
                        .HasForeignKey("CommentId");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Media", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Post", "Post")
                        .WithMany("Medias")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.PostLiker", b =>
                {
                    b.HasOne("Sonorus.PostAPI.Data.Entities.Post", null)
                        .WithMany("Likers")
                        .HasForeignKey("PostId");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Comment", b =>
                {
                    b.Navigation("Likers");
                });

            modelBuilder.Entity("Sonorus.PostAPI.Data.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likers");

                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
