include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    avoid_web_libraries_in_flutter: false
    always_use_package_imports: true
    prefer_double_quotes: true
    unnecessary_await_in_return: true
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_unused_constructor_parameters: true
    always_declare_return_types: true
    curly_braces_in_flow_control_structures: false
    unnecessary_this: false